var GAME_LEVELS = [
  ["x                                                                                      x",
   "x                                                                                      x",
   "x                                                                                      x",
   "x  t                                                                                   x",
   "x                                                                                      x",
   "xffff                                                t         t                       x",
   "x  xxff                     t                                                          x",
   "x    xxff                                           ffff    ffff                       x",
   "x      xxfffffff                 yyy                 xx              ff                x",
   "x                           yyyyyy       t      ff                  xxxfff   fff  fffffx",
   "x                   fffff                    fffxx                                     x",
   "x        t                               ff                      t                     x",
   "x             ffff                                                                     x",
   "x        f                           ffffffff                  ffff                    x",
   "x @                              ffffxxxxxffff              f                          x",
   "xffffffffffffffffffffffff      fffxxxxxxxxxxxxffffffffffffffx         fffffffffffffffffx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxwwwwwwxxxx           xxxxxxxxxxxxxxwwwwwwwwwwxxxxxxxxxxxxxxxxxx",
   "x                  xxxxxxxxxxxxx                           xxxxxxxxxxxxx               x",
   "x                                                                                      x"],
  ["x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                                                                                                                   x",
   "x                         t                                                    fffffffff                            x",
   "x                     f       =f                                   yyyy             t xxff                          x",
   "x        yy        xxxxffffffffx                                        yy            xxxxff                        x",
   "x                                                                              yyyyyyyxxxxxxff                      x",
   "x             yyyy                     yy                                             xxxxxxxxff                    x",
   "x                     yy     yyyyyyx              t   t                yyyyyyy        xxxxxxxxxxff                  x",
   "x                      yfffffy     x          f             =f                        xx        xx                  x",
   "x                ff                x          yyyyyyyyyyyyyyyy                        xx  t                         x",
   "x       @                          x                                                  xx                     =      x",
   "xfffffffffffffffffffffffffffffffffffff!!!!!fffffffffffffffffffffffffwwwwwwwwwwwwwwwwwfffffffffffffffffffffffffffffffx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                            x                                                                       x",
   "x                                            x                                                                       x",
   "x                                            x                                                                       x",
   "x  @                     t               t   x                                                                       x",
   "xfffff                                       x                                                                       x",
   "x           fffff      ffff          ffffff xx                                                                       x",
   "x              xxwwwwwxx  xxwwwwwwwwwxx   xxxx                                                                       x",
   "x    yy         xwwwxxx   xxxxwwwwwxxx                                                                               x",
   "x                 w      t      ww                                                                                   x",
   "x                              www                                                                                   x",
   "x                      yyyyy                                                                                         x",
   "x        yyyyy                       yy           ff   ff                               t                            x",
   "x  t             www            www        t    ffwwwwwwwff                                                          x",
   "x         =  x   www            www           ffwwwwwwwwwwwff                   ff                                   x",
   "xxxxxxxxxxxxxx   www   xxxxxx   www   xxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxx                     x",
   "x            x   www   x    x   www   x          x     t      x                         ff x   x               t     x",
   "x            x   www   x    x   www   x                                      x     fff     x   x     =  =            x",
   "xxxxxxxxxxxxxxwwwwwwwwwxxxxxxwwwwwwwwwxxxxxxxxxxxxwwwwfffwwwwwxxxxxxxxxxxxxxxxwwwwwwwwwwwwwxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
